  module.exports = (sequelize,Sequelize) => {
   var Category  =  sequelize.define("FOODCATEGORY", {

   Category_Id :  {

           type             : Sequelize.INTEGER(150),
           autoIncrement    : true,
           allowNull        : false,
           primaryKey       : true,
           autoGenerated    : true,

   },
   Category_Name:{

           type             : Sequelize.STRING(255),
           allowNull        : false

   },
   Category_Image :{
           type             : Sequelize.STRING(255),
           allowNull        : false
   },
   Category_Status :{
           type             : Sequelize.INTEGER(11),
           allowNull        : false,
           defaultValue     : 1
   }

   },{

           createdAt : false,
           updatedAt : false,
           freezeTableName : true

   });



   Category.removeAttribute("id");
  return Category;

    };
