 module.exports = (sequelize,Sequelize) => {

   var Item = sequelize.define("ADD_ONS",{

	AddOn_Id:{

            type           : Sequelize.INTEGER(150),
            autoIncrement  : true,
            primaryKey     : true,
            allowNull      : false,
            autoGenerated  : true,

  },

   	Inventory_Name : {

           type            : Sequelize.STRING(255),
           allowNull       : false
  },

  Inventory_Id   : {

           type            : Sequelize.INTEGER(150),
           allowNull       : false
  },


  Price  : {

           type            : Sequelize.FLOAT(50,2),
           allowNull       : false

  }
}
 ,{

            createdAt       : false,
            updatedAt       : false,
            freezeTableName : true

   });


       Item.removeAttribute("id");

       return Item;



 };
