module.exports = (sequelize,Sequelize) =>  {

  var Inventory = sequelize.define("INVENTORY",{

  Inventory_Id : {

      type           :  Sequelize.INTEGER(150),
      primaryKey     :  true,
      autoIncrement  :  true,
      autoGenerated  :  true,
      allowNull      :  false

  },

  Inventory_Name  : {

      type           :  Sequelize.STRING(255),
      allowNull      :  false

  },

  Inventory_Quantity : {

      type           :  Sequelize.INTEGER(100),
      allowNull      :  true

  },

  Is_Addon  : {

    type           :  Sequelize.STRING(11),
    allowNull      :  false,
    defaultValue   :  0

  }
},{

    createdAt      : false,
    updatedAt      : false,
    freezeTableName: true

}
);

Inventory.removeAttribute("id");
return Inventory;

};
