

var moment = require("moment");

module.exports = (sequelize,Sequelize) =>{

const Customer = sequelize.define('CUSTOMER_DETAIL',{



Customer_Id :{

					type             : Sequelize.INTEGER(50),
					autoIncrement    : true,
					allowNull        : false,
					primaryKey       : true,
					autoGenerated    : true,



},

Customer_Name  :   {

		type:Sequelize.STRING(255),
		allowNull : false,


},


Customer_Phone_Number : {

		type:Sequelize.INTEGER(20),
		allowNull : false,



},


Customer_Email  :  {

		type:Sequelize.STRING(255),
		allowNull : true,
		// validate:{
		// 					 isEmail : true,
		// 			 }


},

Date_Of_Birth  :  {

		type:Sequelize.DATEONLY,
		allowNull  : true,

		get: function() {
			 return moment.utc(this.getDataValue('Date_Of_Birth')).format('DD-MM-YYYY')
		}
},

User_Category  :  {

		type:Sequelize.STRING(255),
		allowNull : false,
		defaultValue : "customer"

},

Customer_Status   :  {
		type:Sequelize.INTEGER(11),
		allowNull : false,
		defaultValue : 1

},

Count  :  {

		type:Sequelize.INTEGER(11),
		allowNull : false,
		defaultValue : 1
}




},{

	updatedAt:false,

	createdAt: false,

	freezeTableName: true


});


Customer.removeAttribute('id');

return Customer;

}
